name: Update + Push Daily Update
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python ./src/main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily Update
